2020-09-10 10:31:11  [ TestNG-tests-1:0 ] - [ INFO ]  Test applyContinueTest Starts
2020-09-10 10:31:18  [ TestNG-tests-1:7181 ] - [ INFO ]  Test Method testApplyContinue executing...
2020-09-10 10:31:19  [ TestNG-tests-1:8417 ] - [ INFO ]  在该元素下：.//*[@id='credential'],输入内容：SQ
2020-09-10 10:31:20  [ TestNG-tests-1:9376 ] - [ INFO ]  在该元素下：password,输入内容：4HOZvp2y
2020-09-10 10:31:21  [ TestNG-tests-1:10301 ] - [ INFO ]  点击了：//*[@id="account-login-form"]/nz-form-item[3]/nz-form-control/div/span/button
2020-09-10 10:31:31  [ TestNG-tests-1:20700 ] - [ ERROR ]  该元素不存在：//*[@id="setting"]/a
2020-09-10 10:31:32  [ TestNG-tests-1:21217 ] - [ INFO ]  Test run has failed
2020-09-10 10:31:32  [ TestNG-tests-1:21217 ] - [ ERROR ]  检查点不通过 expected [true] but found [false]
2020-09-10 10:31:32  [ TestNG-tests-1:21218 ] - [ ERROR ]  java.lang.AssertionError: 检查点不通过 expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at test.ApplyContinueTest.testApplyContinue(ApplyContinueTest.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-09-10 10:31:32  [ TestNG-tests-1:21457 ] - [ INFO ]  Test applyContinueTest Ends
2020-09-10 10:31:32  [ TestNG-tests-1:21458 ] - [ INFO ]  ---------------------------------------------------------
2020-09-10 10:37:56  [ TestNG-tests-1:0 ] - [ INFO ]  Test applyContinueTest Starts
2020-09-10 10:38:03  [ TestNG-tests-1:7386 ] - [ INFO ]  Test Method testApplyContinue executing...
2020-09-10 10:38:05  [ TestNG-tests-1:8688 ] - [ INFO ]  在该元素下：.//*[@id='credential'],输入内容：SQ
2020-09-10 10:38:06  [ TestNG-tests-1:9658 ] - [ INFO ]  在该元素下：password,输入内容：4HOZvp2y
2020-09-10 10:38:07  [ TestNG-tests-1:10559 ] - [ INFO ]  点击了：//*[@id="account-login-form"]/nz-form-item[3]/nz-form-control/div/span/button
2020-09-10 10:38:17  [ TestNG-tests-1:21013 ] - [ ERROR ]  该元素不存在：//*[@id="setting"]/a
2020-09-10 10:38:18  [ TestNG-tests-1:21595 ] - [ INFO ]  Test run has failed
2020-09-10 10:38:18  [ TestNG-tests-1:21596 ] - [ ERROR ]  检查点不通过 expected [true] but found [false]
2020-09-10 10:38:18  [ TestNG-tests-1:21597 ] - [ ERROR ]  java.lang.AssertionError: 检查点不通过 expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at test.ApplyContinueTest.testApplyContinue(ApplyContinueTest.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-09-10 10:38:18  [ TestNG-tests-1:21859 ] - [ INFO ]  Test applyContinueTest Ends
2020-09-10 10:38:18  [ TestNG-tests-1:21860 ] - [ INFO ]  ---------------------------------------------------------
